services:
  painforglory_loginserver:
    image: ${DOCKER_REGISTRY-}painforgloryloginserver
    build:
      context: PainForGlory_LoginServer
      dockerfile: Dockerfile

  painforglory_server:
    image: ${DOCKER_REGISTRY-}painforgloryserver
    build:
      context: .
      dockerfile: PainforGlory_Server/Dockerfile
  painforglory_web:
    image: ${DOCKER_REGISTRY-}painforgloryweb
    build:
      context: .
      dockerfile: PainForGlory_Web/Dockerfile

